networks:
  green_network:
    external: true

services:
  prometheus_green:
    container_name: prometheus_green
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - green_network
    ports:
      - "9091:9090"

  alertmanager_green:
    container_name: alertmanager_green
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9094:9093"
    networks:
      - green_network

  grafana_green:
    container_name: grafana_green
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - green_network
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data_green:/var/lib/grafana
    depends_on:
      - prometheus_green

 # elasticsearch:
 #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
 #   environment:
 #     - discovery.type=single-node
 #   ports:
  #    - "9200:9200"

  #logstash:
  #  image: docker.elastic.co/logstash/logstash:7.17.0
  #  volumes:
  #    - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #  ports:
  #    - "5020:5000"

 # kibana:
 #   image: docker.elastic.co/kibana/kibana:7.17.0
 #   ports:
 #     - "5601:5601"

volumes:
  grafana_data_green: