{
 "title": "Memoria",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Descriptores de Archivo Abiertos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de Memoria (Virtual y Residente)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{Memoria Resident (Bytes)}}" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes",
     "legendFormat": "{{Uso de CPU (segundos/minuto)}}"
    }
   ]
  }
 ]
}