{
 "title": "Rendimiento de Solicitudes",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Porcentaje de Respuestas Exitosas vs Errores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_total[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia de Solicitudes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket[5m])) by (le, view))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Solicitudes (por vista y método)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(django_view_requests_total[1m])) by (view, method) * 60 \n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}