global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'web'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['web:8000']
        labels:
          alias: "web"

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]

  - job_name: 'mysqld'
    static_configs:
      - targets: [ 'mysqld_exporter:9104' ]

