services:
  nginx_proxy:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "80:80"
    #volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro

    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    networks:
        - my_network
        - green_network
networks:
  my_network:
    external: true
  green_network:
    external: true