# Generated by Django 5.2 on 2025-04-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_response_delete_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
