- name: Remove Blue Deployment Containers
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # LIST OF NAMES OF CONTAINERS USED IN THE DEPLOYMENT ENVIRONMENT
    deployment_containers:
      - backend-web-1
      - backend-db-1
      - backend-postgres_exporter-1
      - metrics-grafana-1
      - metrics-prometheus-1
      - metrics-alertmanager-1
      - webhook
      - frontend-survey-1
      - backend-mysqld_exporter-1

  tasks:
    - name: Show current deployment containers
      debug:
        msg: "Se intentará eliminar los contenedores: {{ deployment_containers }}"

    - name: Remove Container if Exists
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ deployment_containers }}"
      ignore_errors: yes
      # WITH 'ignore_errors:' CONTINUE IF CONTAINER NOT FOUND/EXISTS

    - name: Show Remaining Containers
      command: docker ps -a --format "{{ '{{.Names}}' }}"
      register: docker_list

    - name: List Remaining Containers
      debug:
        msg: "Contenedores restantes en el host: {{ docker_list.stdout_lines }}"